### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by mathigatti** [jhyrkas/wavaetable#1]
Hi! It looks nice, thanks for sharing!

By any chance do you have a sound sample to check it and a trained model to try it?

**Comment by jhyrkas** [comment]
Hi Mathias,

Thanks for checking this out! I think the trained model should be uploaded as vae_stft_model_params.pytorch, you can also train the model from scratch by getting the data and then training the model (the instructions should be on the README). Please let me know if you have any trouble with that.

I did want to also point out that this model is not particularly interesting; in my opinion, what is more interesting is using the Max or Supercollider patches to interact with the model! You can also use the canne model, which has a better sound...those instructions are also at the bottom of the README. Or you can drop in your own favorite VAE! All you need is to modify a couple of scripts.

Anyway, please let me know if you have any issues!

-Jeremy

**Comment by mathigatti** [comment]
Amazing thanks! I'm testing it. I'm looking for a fast audio VAE to use in live shows. Do you have any recommendations about that?

I want to use it mostly for voice/singing effects

**Comment by jhyrkas** [comment]
For real-time synthesis, you could look into the [canne synthesizer](https://github.com/JTColonel/canne_synth), or other work by [Joseph Colonel](https://github.com/JTColonel). You could also use this library to generate interesting sounds in near-real time or ahead of time, then the wavetable synthesis in Max or SuperCollider is in real time.

Now that said, these libraries are designed as synthesizers, i.e. they take a latent space input and produce output audio. For a vocal effect, you would need to retrain these libraries on vocal data and they would still operate from a latent space input. If you want to effect your voice in a live scenario, you might need to rethink the training process or train a different model depending on what you are trying to do.
